<?php

########################################################################
# Extension Manager/Repository config file for ext: "dfki_staff_db"
#
# Auto generated by Extension Builder 2012-08-14
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = [
    'title' => 'myDFKI Schnittstelle',
    'description' => 'myDFKI DB-Schnittstelle zum Anzeigen der Mitarbeiter und Publikationen in verschiedenen Ansichten.',
    'category' => 'plugin',
    'author' => 'Dipl.-Inf. Veit Briken',
    'author_email' => 'veit.briken@dfki.de',
    'author_company' => 'DFKI GmbH',
    'state' => 'stable',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '10.0.3',
    'autoload' => array('psr-4' => array('DFKI\DfkiStaffDb\\' => 'Classes')),
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
